#!/bin/bash
echo "***********************************************************"
echo "*** Welcome to the SAMA7G54-Ek Demos selection menu     ***"
echo "***     Made with love by the MPU32 Marketing Team      ***"
echo "***********************************************************"
#submenu audio
submenu_audio () {
  local PS3='
Press [ENTER] to display the options if they are not shown
Please choose an option :
'
  local options=("Button Launched Keyword recognition" "Perpetual Keyword Recognition" "Quit audio menu")
  local opt
  select opt in "${options[@]}"
  do
      case $opt in
          "Button Launched Keyword recognition")
              cd keyword_recognition
              python3 ./audio_reco_inference_button.py
              cd
              ;;
          "Perpetual Keyword Recognition")
              cd keyword_recognition
              python3 ./audio_reco_inference.py
              cd
              ;;
          "Quit audio menu")
              return
              ;;
          *) echo "invalid option $REPLY";;
      esac
  done
}
#submenu image
submenu_image () {
  local PS3='
Press [ENTER] to display the options if they are not shown
Please choose an option :
'
  local options=("MIPI CAM : Dynamic Object Recognition" "USB CAM : Dynamic demo using user button" "USB CAM :Infinite dynamic demo" "Quit object recognition menu")
  local opt
  select opt in "${options[@]}"
  do
      case $opt in
          "MIPI CAM : Dynamic Object Recognition")
            cd image_classification
            cd MIPI_Camera
            python3 ./mipi_object_reco_flask.py
            cd
            ;;
          "USB CAM : Dynamic demo using user button")
            cd image_classification
            cd USB_Camera
            python3 ./img_reco_with_pressed_button.py
            cd
            ;;
        "USB CAM :Infinite dynamic demo")
            cd image_classification
            cd USB_Camera
            python3 ./infinite_camera_object_reco.py
            cd
            ;;
          "Quit object recognition menu")
              return
              ;;
          *) echo "invalid option $REPLY";;
      esac
  done
}
PS3='
Press [ENTER] to display the options if they are not shown
Please choose an option :
'
options=("Object recognition demos" "Keyword recognition demos" "Automatic License Plate Recognition demo" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Object recognition demos")
            echo ""
            submenu_image
            ;;
        "Keyword recognition demos")
            echo ""
            submenu_audio
            ;;
        "Automatic License Plate Recognition demo")
        cd ALPR
        python3 ./ALPR_tflite.py
        cd
        ;;
        "Quit")
            echo "***Thanks for using this menu***"
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done